Started logging messages at Thu Jul 25 15:48:00 2019
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 0 B-reps in file
Info:    Found 6324 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Created 
Info:    Working on 1
Info:        Created 
Info:    Working on 2
Info:        Created 
Info:    Working on 3
Info:        Created 
Info:    Working on 4
Info:        Created 
Info:    Working on 5
Info:        Created 
Info:    Working on 6
Info:        Created 
Info:    Working on 7
Info:        Created 
Info:    Working on 8
Info:        Created 
Info:    Working on 9
Info:        Created 
Info:    Working on 10
Info:        Created 
Info:    Working on 11
Info:        Created 
Info:    Working on 12
Info:        Created 
Info:    Working on 13
Info:        Created 
Info:    Working on 14
Info:        Created 
Info:    Working on 15
Info:        Created 
Info:    Working on 16
Info:        Created 
Info:    Working on 17
Info:        Created 
Info:    Working on 18
Info:        Created 
Info:    Working on 19
Info:        Created 
Info:    Working on 20
Info:        Created 
Info:    Working on 21
Info:        Created 
Info:    Working on 22
Info:        Created 
Info:    Working on 23
Info:        Created 
Info:    Working on 24
Info:        Created 
Info:    Working on 25
Info:        Created 
Info:    Working on 26
Info:        Created 
Info:    Working on 27
Info:        Created 
Info:    Working on 28
Info:        Created 
Info:    Working on 29
Info:        Created 
Info:    Working on 30
Info:        Created 
Info:    Working on 31
Info:        Created 
Info:    Working on 32
Info:        Created 
Info:    Working on 33
Info:        Created 
Info:    Working on 34
Info:        Created 
Info:    Working on 35
Info:        Created 
Info:    Working on 36
Info:        Created 
Info:    Working on 37
Info:        Created 
Info:    Working on 38
Info:        Created 
Info:    Working on 39
Info:        Created 
Info:    Working on 40
Info:        Created 
Info:    Working on 41
Info:        Created 
Info:    Working on 42
Info:        Created 
Info:    Working on 43
Info:        Created 
Info:    Working on 44
Info:        Created 
Info:    Working on 45
Info:        Created 
Info:    Working on 46
Info:        Created 
Info:    Working on 47
Info:        Created 
Info:    Working on 48
Info:        Created 
Info:    Working on 49
Info:        Created 
Info:    Working on 50
Info:        Created 
Info:    Working on 51
Info:        Created 
Info:    Working on 52
Info:        Created 
Info:    Working on 53
Info:        Created 
Info:    Working on 54
Info:        Created 
Info:    Working on 55
Info:        Created 
Info:    Working on 56
Info:        Created 
Info:    Working on 57
Info:        Created 
Info:    Working on 58
Info:        Created 
Info:    Working on 59
Info:        Created 
Info:    Working on 60
Info:        Created 
Info:    Working on 61
Info:        Created 
Info:    Working on 62
Info:        Created 
Info:    Working on 63
Info:        Created 
Info:    Working on 64
Info:        Created 
Info:    Working on 65
Info:        Created 
Info:    Working on 66
Info:        Created 
Info:    Working on 67
Info:        Created 
Info:    Working on 68
Info:        Created 
Info:    Working on 69
Info:        Created 
Info:    Working on 70
Info:        Created 
Info:    Working on 71
Info:        Created 
Info:    Working on 72
Info:        Created 
Info:    Working on 73
Info:        Created 
Info:    Working on 74
Info:        Created 
Info:    Working on 75
Info:        Created 
Info:    Working on 76
Info:        Created 
Info:    Working on 77
Info:        Created 
Info:    Working on 78
Info:        Created 
Info:    Working on 79
Info:        Created 
Info:    Working on 80
Info:        Created 
Info:    Working on 81
Info:        Created 
Info:    Working on 82
Info:        Created 
Info:    Working on 83
Info:        Created 
Info:    Working on 84
Info:        Created 
Info:    Working on 85
Info:        Created 
Info:    Working on 86
Info:        Created 
Info:    Working on 87
Info:        Created 
Info:    Working on 88
Info:        Created 
Info:    Working on 89
Info:        Created 
Info:    Working on 90
Info:        Created 
Info:    Working on 91
Info:        Created 
Info:    Working on 92
Info:        Created 
Info:    Working on 93
Info:        Created 
Info:    Working on 94
Info:        Created 
Info:    Working on 95
Info:        Created 
Info:    Working on 96
Info:        Created 
Info:    Working on 97
Info:        Created 
Info:    Working on 98
Info:        Created 
Info:    Working on 99
Info:        Created 
Info:    Working on 100
Info:        Created 
Info:    Working on 101
Info:        Created 
Info:    Working on 102
Info:        Created 
Info:    Working on 103
Info:        Created 
Info:    Working on 104
Info:        Created 
Info:    Working on 105
Info:        Created 
Info:    Working on 106
Info:        Created 
Info:    Working on 107
Info:        Created 
Info:    Working on 108
Info:        Created 
Info:    Working on 109
Info:        Created 
Info:    Working on 110
Info:        Created 
Info:    Working on 111
Info:        Created 
Info:    Working on 112
Info:        Created 
Info:    Working on 113
Info:        Created 
Info:    Working on 114
Info:        Created 
Info:    Working on 115
Info:        Created 
Info:    Working on 116
Info:        Created 
Info:    Working on 117
Info:        Created 
Info:    Working on 118
Info:        Created 
Info:    Working on 119
Info:        Created 
Info:    Working on 120
Info:        Created 
Info:    Working on 121
Info:        Created 
Info:    Working on 122
Info:        Created 
Info:    Working on 123
Info:        Created 
Info:    Working on 124
Info:        Created 
Info:    Working on 125
Info:        Created 
Info:    Working on 126
Info:        Created 
Info:    Working on 127
Info:        Created 
Info:    Working on 128
Info:        Created 
Info:    Working on 129
Info:        Created 
Info:    Working on 130
Info:        Created 
Info:    Working on 131
Info:        Created 
Info:    Working on 132
Info:        Created 
Info:    Working on 133
Info:        Created 
Info:    Working on 134
Info:        Created 
Info:    Working on 135
Info:        Created 
Info:    Working on 136
Info:        Created 
Info:    Working on 137
Info:        Created 
Info:    Working on 138
Info:        Created 
Info:    Working on 139
Info:        Created 
Info:    Working on 140
Info:        Created 
Info:    Working on 141
Info:        Created 
Info:    Working on 142
Info:        Created 
Info:    Working on 143
Info:        Created 
Info:    Working on 144
Info:        Created 
Info:    Working on 145
Info:        Created 
Info:    Working on 146
Info:        Created 
Info:    Working on 147
Info:        Created 
Info:    Working on 148
Info:        Created 
Info:    Working on 149
Info:        Created 
Info:    Working on 150
Info:        Created 
Info:    Working on 151
Info:        Created 
Info:    Working on 152
Info:        Created 
Info:    Working on 153
Info:        Created 
Info:    Working on 154
Info:        Created 
Info:    Working on 155
Info:        Created 
Info:    Working on 156
Info:        Created 
Info:    Working on 157
Info:        Created 
Info:    Working on 158
Info:        Created 
Info:    Working on 159
Info:        Created 
Info:    Working on 160
Info:        Created 
Info:    Working on 161
Info:        Created 
Info:    Working on 162
Info:        Created 
Info:    Working on 163
Info:        Created 
Info:    Working on 164
Info:        Created 
Info:    Working on 165
Info:        Created 
Info:    Working on 166
Info:        Created 
Info:    Working on 167
Info:        Created 
Info:    Working on 168
Info:        Created 
Info:    Working on 169
Info:        Created 
Info:    Working on 170
Info:        Created 
Info:    Working on 171
Info:        Created 
Info:    Working on 172
Info:        Created 
Info:    Working on 173
Info:        Created 
Info:    Working on 174
Info:        Created 
Info:    Working on 175
Info:        Created 
Info:    Working on 176
Info:        Created 
Info:    Working on 177
Info:        Created 
Info:    Working on 178
Info:        Created 
Info:    Working on 179
Info:        Created 
Info:    Working on 180
Info:        Created 
Info:    Working on 181
Info:        Created 
Info:    Working on 182
Info:        Created 
Info:    Working on 183
Info:        Created 
Info:    Working on 184
Info:        Created 
Info:    Working on 185
Info:        Created 
Info:    Working on 186
Info:        Created 
Info:    Working on 187
Info:        Created 
Info:    Working on 188
Info:        Created 
Info:    Working on 189
Info:        Created 
Info:    Working on 190
Info:        Created 
Info:    Working on 191
Info:        Created 
Info:    Working on 192
Info:        Created 
Info:    Working on 193
Info:        Created 
Info:    Working on 194
Info:        Created 
Info:    Working on 195
Info:        Created 
Info:    Working on 196
Info:        Created 
Info:    Working on 197
Info:        Created 
Info:    Working on 198
Info:        Created 
Info:    Working on 199
Info:        Created 
Info:    Working on 200
Info:        Created 
Info:    Working on 201
Info:        Created 
Info:    Working on 202
Info:        Created 
Info:    Working on 203
Info:        Created 
Info:    Working on 204
Info:        Created 
Info:    Working on 205
Info:        Created 
Info:    Working on 206
Info:        Created 
Info:    Working on 207
Info:        Created 
Info:    Working on 208
Info:        Created 
Info:    Working on 209
Info:        Created 
Info:    Working on 210
Info:        Created 
Info:    Working on 211
Info:        Created 
Info:    Working on 212
Info:        Created 
Info:    Working on 213
Info:        Created 
Info:    Working on 214
Info:        Created 
Info:    Working on 215
Info:        Created 
Info:    Working on 216
Info:        Created 
Info:    Working on 217
Info:        Created 
Info:    Working on 218
Info:        Created 
Info:    Working on 219
Info:        Created 
Info:    Working on 220
Info:        Created 
Info:    Working on 221
Info:        Created 
Info:    Working on 222
Info:        Created 
Info:    Working on 223
Info:        Created 
Info:    Working on 224
Info:        Created 
Info:    Working on 225
Info:        Created 
Info:    Working on 226
Info:        Created 
Info:    Working on 227
Info:        Created 
Info:    Working on 228
Info:        Created 
Info:    Working on 229
Info:        Created 
Info:    Working on 230
Info:        Created 
Info:    Working on 231
Info:        Created 
Info:    Working on 232
Info:        Created 
Info:    Working on 233
Info:        Created 
Info:    Working on 234
Info:        Created 
Info:    Working on 235
Info:        Created 
Info:    Working on 236
Info:        Created 
Info:    Working on 237
Info:        Created 
Info:    Working on 238
Info:        Created 
Info:    Working on 239
Info:        Created 
Info:    Working on 240
Info:        Created 
Info:    Working on 241
Info:        Created 
Info:    Working on 242
Info:        Created 
Info:    Working on 243
Info:        Created 
Info:    Working on 244
Info:        Created 
Info:    Working on 245
Info:        Created 
Info:    Working on 246
Info:        Created 
Info:    Working on 247
Info:        Created 
Info:    Working on 248
Info:        Created 
Info:    Working on 249
Info:        Created 
Info:    Working on 250
Info:        Created 
Info:    Working on 251
Info:        Created 
Info:    Working on 252
Info:        Created 
Info:    Working on 253
Info:        Created 
Info:    Working on 254
Info:        Created 
Info:    Working on 255
Info:        Created 
Info:    Working on 256
Info:        Created 
Info:    Working on 257
Info:        Created 
Info:    Working on 258
Info:        Created 
Info:    Working on 259
Info:        Created 
Info:    Working on 260
Info:        Created 
Info:    Working on 261
Info:        Created 
Info:    Working on 262
Info:        Created 
Info:    Working on 263
Info:        Created 
Info:    Working on 264
Info:        Created 
Info:    Working on 265
Info:        Created 
Info:    Working on 266
Info:        Created 
Info:    Working on 267
Info:        Created 
Info:    Working on 268
Info:        Created 
Info:    Working on 269
Info:        Created 
Info:    Working on 270
Info:        Created 
Info:    Working on 271
Info:        Created 
Info:    Working on 272
Info:        Created 
Info:    Working on 273
Info:        Created 
Info:    Working on 274
Info:        Created 
Info:    Working on 275
Info:        Created 
Info:    Working on 276
Info:        Created 
Info:    Working on 277
Info:        Created 
Info:    Working on 278
Info:        Created 
Info:    Working on 279
Info:        Created 
Info:    Working on 280
Info:        Created 
Info:    Working on 281
Info:        Created 
Info:    Working on 282
Info:        Created 
Info:    Working on 283
Info:        Created 
Info:    Working on 284
Info:        Created 
Info:    Working on 285
Info:        Created 
Info:    Working on 286
Info:        Created 
Info:    Working on 287
Info:        Created 
Info:    Working on 288
Info:        Created 
Info:    Working on 289
Info:        Created 
Info:    Working on 290
Info:        Created 
Info:    Working on 291
Info:        Created 
Info:    Working on 292
Info:        Created 
Info:    Working on 293
Info:        Created 
Info:    Working on 294
Info:        Created 
Info:    Working on 295
Info:        Created 
Info:    Working on 296
Info:        Created 
Info:    Working on 297
Info:        Created 
Info:    Working on 298
Info:        Created 
Info:    Working on 299
Info:        Created 
Info:    Working on 300
Info:        Created 
Info:    Working on 301
Info:        Created 
Info:    Working on 302
Info:        Created 
Info:    Working on 303
Info:        Created 
Info:    Working on 304
Info:        Created 
Info:    Working on 305
Info:        Created 
Info:    Working on 306
Info:        Created 
Info:    Working on 307
Info:        Created 
Info:    Working on 308
Info:        Created 
Info:    Working on 309
Info:        Created 
Info:    Working on 310
Info:        Created 
Info:    Working on 311
Info:        Created 
Info:    Working on 312
Info:        Created 
Info:    Working on 313
Info:        Created 
Info:    Working on 314
Info:        Created 
Info:    Working on 315
Info:        Created 
Info:    Working on 316
Info:        Created 
Info:    Working on 317
Info:        Created 
Info:    Working on 318
Info:        Created 
Info:    Working on 319
Info:        Created 
Info:    Working on 320
Info:        Created 
Info:    Working on 321
Info:        Created 
Info:    Working on 322
Info:        Created 
Info:    Working on 323
Info:        Created 
Info:    Working on 324
Info:        Created 
Info:    Working on 325
Info:        Created 
Info:    Working on 326
Info:        Created 
Info:    Working on 327
Info:        Created 
Info:    Working on 328
Info:        Created 
Info:    Working on 329
Info:        Created 
Info:    Working on 330
Info:        Created 
Info:    Working on 331
Info:        Created 
Info:    Working on 332
Info:        Created 
Info:    Working on 333
Info:        Created 
Info:    Working on 334
Info:        Created 
Info:    Working on 335
Info:        Created 
Info:    Working on 336
Info:        Created 
Info:    Working on 337
Info:        Created 
Info:    Working on 338
Info:        Created 
Info:    Working on 339
Info:        Created 
Info:    Working on 340
Info:        Created 
Info:    Working on 341
Info:        Created 
Info:    Working on 342
Info:        Created 
Info:    Working on 343
Info:        Created 
Info:    Working on 344
Info:        Created 
Info:    Working on 345
Info:        Created 
Info:    Working on 346
Info:        Created 
Info:    Working on 347
Info:        Created 
Info:    Working on 348
Info:        Created 
Info:    Working on 349
Info:        Created 
Info:    Working on 350
Info:        Created 
Info:    Working on 351
Info:        Created 
Info:    Working on 352
Info:        Created 
Info:    Working on 353
Info:        Created 
Info:    Working on 354
Info:        Created 
Info:    Working on 355
Info:        Created 
Info:    Working on 356
Info:        Created 
Info:    Working on 357
Info:        Created 
Info:    Working on 358
Info:        Created 
Info:    Working on 359
Info:        Created 
Info:    Working on 360
Info:        Created 
Info:    Working on 361
Info:        Created 
Info:    Working on 362
Info:        Created 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  0 found       0 created       0 failed
Finished logging messages at Thu Jul 25 15:48:02 2019
